In [48]:
from __future__ import division, print_function, absolute_import

import numpy as np
import matplotlib.pyplot as plt

import importlib
import nptdms
import pickle

from os import path

from peak_finder import utilities as util
from peak_finder import generate_lorentz as gl
from peak_finder import generate_data as gd
from peak_finder import classify_data as cd
from peak_finder import efficient_data_generation as ed
from peak_finder import data_spy as ds
from peak_finder import sliding_window as sw
from peak_finder import train_model as tm
from peak_finder import fit_lorentz as fl
from peak_finder import live_fitting as lf
from peak_finder import track_peaks as tp
from peak_finder import background_removal as br
from peak_finder import automatic as auto
from peak_finder import models

importlib.reload(util)
importlib.reload(gl)
importlib.reload(gd)
importlib.reload(cd)
importlib.reload(ed)
importlib.reload(ds)
importlib.reload(sw)
importlib.reload(tm)
importlib.reload(fl)
importlib.reload(lf)
importlib.reload(tp)
importlib.reload(br)
importlib.reload(auto)
importlib.reload(models)

&lt;module &#39;peak_finder.models&#39; from &#39;/home/Gabriel-Linux-Desktop/Documents/ML-Peak-Tracker/peak_finder/models.py&#39;&gt;

In [22]:
data_files = util.import_tdms_dir(show=True)
print(len(data_files))
# p = util.load()
# util.set_all_params(data_files, p)

/home/Gabriel-Linux-Desktop/Desktop/AG3117 - III/2_setup
/home/Gabriel-Linux-Desktop/Desktop/AG3117 - III/2_setup
39


In [49]:
df = util.import_tdms_files(show=True)

Imported file order:
0:  20200925_212312_298.351K_298.351K
1:  20200925_212630_298.426K_298.426K
2:  20200925_212946_298.513K_298.513K
3:  20200925_213842_298.558K_298.558K
4:  20200925_215257_298.575K_298.575K
5:  20200925_221517_298.959K_298.959K
6:  20200925_223058_298.834K_298.834K
7:  20200925_225926_298.818K_297.844K
8:  20200925_233626_297.303K_297.873K
9:  20200928_140053_298.321K_298.321K
10: 20200928_151503_300.456K_300.458K
11: 20200928_153322_300.548K_300.484K


In [4]:
p0, p1 = util.load(), util.load()

In [5]:
p0 = lf.live_selection(df[0])

In [6]:
util.set_all_params(df, p)

In [15]:
lf.point_selection(df)

array([], dtype=float64)

In [24]:
p = lf.color_selection(data_files)

/home/Gabriel-Linux-Desktop/Documents/ML-Peak-Tracker/peak_finder/live_fitting.py:1360: MatplotlibDeprecationWarning: shading=&#39;flat&#39; when X and Y have the same dimensions as C is deprecated since 3.3.  Either specify the corners of the quadrilaterals with X and Y, or pass shading=&#39;auto&#39;, &#39;nearest&#39; or &#39;gouraud&#39;, or set rcParams[&#39;pcolor.shading&#39;].  This will become an error two minor releases later.
  colors = ax.pcolormesh(color_x, color_y, z, cmap=cmap)
/home/Gabriel-Linux-Desktop/Documents/ML-Peak-Tracker/peak_finder/live_fitting.py:880: MatplotlibDeprecationWarning: shading=&#39;flat&#39; when X and Y have the same dimensions as C is deprecated since 3.3.  Either specify the corners of the quadrilaterals with X and Y, or pass shading=&#39;auto&#39;, &#39;nearest&#39; or &#39;gouraud&#39;, or set rcParams[&#39;pcolor.shading&#39;].  This will become an error two minor releases later.
  self.enhanced_renders.append(self.ax.pcolormesh(color_x, col

In [16]:
p = lf.mistake_selection(data_files, p)

AttributeError: &#39;NoneType&#39; object has no attribute &#39;rint&#39;

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File &quot;/home/Gabriel-Linux-Desktop/.local/lib/python3.8/site-packages/matplotlib/cbook/__init__.py&quot;, line 224, in process
    func(*args, **kwargs)
  File &quot;/home/Gabriel-Linux-Desktop/Documents/ML-Peak-Tracker/peak_finder/live_fitting.py&quot;, line 1248, in on_click
    T_ind = int(np.round(event.xdata))
  File &quot;&lt;__array_function__ internals&gt;&quot;, line 5, in round_
  File &quot;/home/Gabriel-Linux-Desktop/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py&quot;, line 3599, in round_
    return around(a, decimals=decimals, out=out)
  File &quot;&lt;__array_function__ internals&gt;&quot;, line 5, in around
  File &quot;/home/Gabriel-Linux-Desktop/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py&quot;, line 3224, in around
    return _wrapfunc(a, &#39;round&#39

In [12]:
p_5 = fl.parameters_from_selections(data_files_5, s)

In [20]:
p_5 = util.load()

In [21]:
p = fl.parameters_from_selections(data_files, s)

In [17]:
p_5[0]

array([[           nan,            nan,            nan,            nan],
       [7.11468543e-05, 4.31786454e+06, 4.98259060e+03, 4.40191289e+00]])

In [23]:
util.set_all_params(data_files, p)

In [45]:
util.save_freqs_with_temps(data_files)

In [145]:
p = fl.denan_parameters(p, 0.99)

In [175]:
t = fl.clean_selections(s)

In [186]:
p.shape

(226, 2, 4)

In [38]:
p0.shape

(226, 8, 4)

In [55]:
p1 = util.attach_temps_to_parameters(data_files)

In [59]:
util.save(p1)

'/home/gabriel/Documents/AG2684_III_3_cooldown_parameters_and_temps_1.pkl'

In [8]:
ds.scatter_data_files(df)

In [22]:
p1 = lf.live_selection(df[1])

In [6]:
df = [data_files[7], data_files[13], data_files[14], data_files[15]]

In [23]:
q = [p0, p1]

In [14]:
p = [p0, p1, p2, p3]

In [24]:
fs = lf.point_selection(df, q)

In [ ]:
plt.scatter(f, np.ones(len(f)))
plt.scatter(f[2:], np.ones(len(f[2:])))

In [89]:
f = np.sort(f) / 1000

In [25]:
util.save_freqs(fs)

In [103]:
np.savetxt('/home/gabriel/Documents/Processed RUS Data/AG3023 - I/1_roomtemp/f0.txt', f, delimiter='\n', fmt='%10.15f')

In [17]:
fs = util.load_freqs()

In [29]:
p.append(q)

In [194]:
np.delete(p, 2)

array([7.62265906e-06, 5.39316247e+06, 2.11002521e+00, ...,
       4.79284121e+06, 2.60078196e+04, 8.79143628e-01])

In [77]:
1600):
    j = i % 40
    if j == 0:
        imgs_2d.append([])
    imgs_2d[i // 40].append(imgs[i])

Generating Data: [========================================] 10000/10000

In [78]:
home = path.expanduser('~')
desktop = path.join(home, 'Desktop')
for i in range(len(v)):
    if int(np.round(l[i])) == 1:
        color = 'g'
    else:
        color = 'r'
    plt.cla()
    plt.plot(np.linspace(0, 1, 1024), v[i], color=color)
    plt.savefig(path.join(desktop, 'frame_' + str(i) + '.png'))

KeyboardInterrupt: 

In [80]:
imgs = []
for i in range(len(v)):
    imgs.append(cv2.imread(path.join(desktop, 'frame_' + str(i) + '.png')))
imgs_2d = []
for i in range(1600):
    j = i % 40
    if j == 0:
        imgs_2d.append([])
    imgs_2d[i // 40].append(imgs[i])

In [41]:

def concat_tile(im_list_2d):
    return cv2.vconcat([cv2.hconcat(im_list_h) for im_list_h in im_list_2d])

In [84]:
tile = concat_tile(imgs_2d)
til = cv2.resize(tile, (0,0),fx=0.5, fy=0.5)

In [85]:
cv2.imwrite(path.join(desktop, str(len(v)) + '_tile.png'), tile)

True

In [4]:
lf.live_selection(data_files[0])

array([], shape=(0, 4), dtype=float64)

In [45]:
sing = ed.make_single_data_set(100)

Generating Data: [========================================] 100/100

In [38]:
f = cd.normalize_1d(sing[1][0], (0, 1, 1024))

In [39]:
f_small = cd.normalize_1d(f, (0, 1, 3))

In [40]:
plt.plot(np.linspace(0, 1, 1024), f)
plt.plot(np.linspace(0, 1, 3), f_small)

In [49]:
ax = plt.axes(projection='3d')
for i in range(len(sing[0])):
    l = sing[0][i]
    if int(l) == 0:
        color = 'r'
    else:
        color = 'g'
    f_small = cd.normalize_1d(sing[1][i], (0, 1, 3))
    ax.scatter3D(f_small[0], f_small[1], f_small[2], color=color)

In [28]:
data_files[225].T

array([5.421 , 5.421 , 5.421 , ..., 5.3067, 5.3067, 5.3067])